/*
 * © 2026 Heady™Systems Inc..
 * Auth Routes — now powered by the dynamic provider registry.
 * All providers are defined in src/auth/provider-registry.js
 * Routes are auto-generated by src/auth/dynamic-auth-router.js
 */
module.exports = require('../auth/dynamic-auth-router');
