name = "edge-composer"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "$CLOUDFLARE_ACCOUNT_ID"

[env.production]
routes = [{ pattern = "compose.headysystems.com/*", zone_name = "headysystems.com" }]
[env.production.vars]
ENVIRONMENT = "production"
COMPOSE_BACKEND = "https://manager.headysystems.com/api/compose"
