module.exports = {
  apps: [
    {
      name: 'heady-manager',
      script: 'heady-manager.js',
      instances: 'max',
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      env_production: {
        NODE_ENV: 'production',
        PORT: 3301,
      },
      error_file: './logs/heady-manager-error.log',
      out_file: './logs/heady-manager-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4236, // phi^3 x 1000
      exp_backoff_restart_delay: 1618, // phi x 1000
      kill_timeout: 5000,
      listen_timeout: 10000,
      shutdown_with_message: true,
      wait_ready: true,
    },
    {
      name: 'hcfp-auto-success',
      script: 'src/orchestration/hc_auto_success.js',
      instances: 1,
      max_memory_restart: '256M',
      env_production: {
        NODE_ENV: 'production',
        AUTO_SUCCESS_CYCLE_MS: 29034,
      },
      error_file: './logs/hcfp-error.log',
      out_file: './logs/hcfp-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4236,
      cron_restart: '0 */4 * * *',
    },
    {
      name: 'api-gateway',
      script: 'src/gateway/index.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '256M',
      env_production: { NODE_ENV: 'production', PORT: 4301 },
      error_file: './logs/api-gateway-error.log',
      out_file: './logs/api-gateway-out.log',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4236,
    },
    {
      name: 'domain-router',
      script: 'src/routing/domain-router.js',
      instances: 1,
      max_memory_restart: '256M',
      env_production: { NODE_ENV: 'production', PORT: 4311 },
      error_file: './logs/domain-router-error.log',
      out_file: './logs/domain-router-out.log',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4236,
    },
    {
      name: 'heady-conductor',
      script: 'src/orchestration/conductor.js',
      instances: 1,
      max_memory_restart: '256M',
      env_production: { NODE_ENV: 'production', PORT: 4306 },
      error_file: './logs/conductor-error.log',
      out_file: './logs/conductor-out.log',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4236,
    },
    {
      name: 'heady-mcp',
      script: 'src/mcp/heady-mcp-server.js',
      instances: 1,
      max_memory_restart: '256M',
      env_production: { NODE_ENV: 'production', PORT: 4317 },
      error_file: './logs/mcp-error.log',
      out_file: './logs/mcp-out.log',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4236,
    },
    {
      name: 'heady-buddy',
      script: 'src/services/buddy-system.js',
      instances: 1,
      max_memory_restart: '256M',
      env_production: { NODE_ENV: 'production', PORT: 4318 },
      error_file: './logs/buddy-error.log',
      out_file: './logs/buddy-out.log',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4236,
    },
    {
      name: 'heady-bee-factory',
      script: 'src/bees/bee-factory.js',
      instances: 1,
      max_memory_restart: '512M',
      env_production: { NODE_ENV: 'production', PORT: 4319 },
      error_file: './logs/bee-factory-error.log',
      out_file: './logs/bee-factory-out.log',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4236,
    }
  ]
};
