// PM2 Ecosystem Configuration
// Manages all Heady AI Platform services
module.exports = {
    apps: [
        // ── Core Services ──
        {
            name: 'heady-manager',
            script: 'heady-manager.js',
            cwd: '/home/headyme/Heady',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
                NODE_TLS_REJECT_UNAUTHORIZED: '0',
                PORT: 3301,
                HF_TOKEN: process.env.HF_TOKEN || '',
            },
            max_memory_restart: '512M',
            min_uptime: '10s',
            max_restarts: 10,
            restart_delay: 3000,
            kill_timeout: 5000,
            listen_timeout: 10000,
            watch: false,
            error_file: '/home/headyme/Heady/logs/manager-error.log',
            out_file: '/home/headyme/Heady/logs/manager-out.log',
            merge_logs: true,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
        },
        {
            name: 'hcfp-auto-success',
            script: 'scripts/hcfp-full-auto.js',
            cwd: '/home/headyme/Heady',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
            },
            max_memory_restart: '256M',
            min_uptime: '10s',
            max_restarts: 5,
            restart_delay: 5000,
            watch: false,
            error_file: '/home/headyme/Heady/logs/hcfp-error.log',
            out_file: '/home/headyme/Heady/logs/hcfp-out.log',
            merge_logs: true,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
        },

        // ── 1ime1 — Direct HeadyBuddy Interface (uses server.js with API proxy) ──
        {
            name: 'site-1ime1',
            script: 'server.js',
            cwd: '/home/headyme/sites/1ime1',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
                PORT: 9016,
                API_TARGET: 'https://127.0.0.1:3301',
            },
            max_memory_restart: '128M',
            min_uptime: '5s',
            max_restarts: 5,
            restart_delay: 2000,
            watch: false,
            autorestart: true,
            error_file: '/home/headyme/Heady/logs/1ime1-error.log',
            out_file: '/home/headyme/Heady/logs/1ime1-out.log',
            merge_logs: true,
        },

        // ── headyme.com — THE entry point (uses server.js with API proxy) ──
        {
            name: 'site-headyme',
            script: 'server.js',
            cwd: '/home/headyme/sites/headyme',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
                PORT: 9005,
                API_TARGET: 'https://manager.headysystems.com',
                HEADY_API_KEY: process.env.HEADY_API_KEY || '',
            },
            max_memory_restart: '128M',
            min_uptime: '5s',
            max_restarts: 5,
            restart_delay: 2000,
            watch: false,
            autorestart: true,
            error_file: '/home/headyme/Heady/logs/headyme-error.log',
            out_file: '/home/headyme/Heady/logs/headyme-out.log',
            merge_logs: true,
        },

        // ── Site Servers ──
        // Each site runs a static file server on its assigned port
        ...[
            // ── Primary Sites ──
            { name: 'headybuddy', port: 9000 },
            { name: 'headysystems', port: 9001 },
            { name: 'headyconnection', port: 9002 },
            { name: 'headymcp', port: 9003 },
            { name: 'headyio', port: 9004 },
            // headyme uses its own server.js (dedicated block above)
            { name: 'headyapi', port: 9006 },
            { name: 'headyos', port: 9007 },
            { name: 'heady-discord', port: 9008 },
            { name: 'heady-discord-connector', port: 9009 },
            { name: 'headyio-com', port: 9010 },
            { name: 'headybuddy-org', port: 9011 },
            { name: 'headyconnection-org', port: 9012 },
            { name: 'headyme-com', port: 9013 },
            { name: 'headymcp-com', port: 9014 },
            { name: 'headysystems-com', port: 9015 },
            // 1ime1 uses its own server.js (moved to dedicated block below)
            { name: 'admin-ui', port: 9017 },
            { name: 'instant', port: 9018 },
            { name: 'headydocs', port: 9019 },
            { name: 'heady-discord-connection', port: 9020 },
            { name: 'headyweb', port: 3000 },
            // ── Vertical Node Sites (26 sites) ──
            { name: 'heady-buddy-portal', port: 9100 },
            { name: 'heady-maestro', port: 9101 },
            { name: 'heady-jules', port: 9102 },
            { name: 'heady-observer', port: 9103 },
            { name: 'heady-builder', port: 9104 },
            { name: 'heady-atlas', port: 9105 },
            { name: 'heady-pythia', port: 9106 },
            { name: 'heady-montecarlo', port: 9107 },
            { name: 'heady-patterns', port: 9108 },
            { name: 'heady-critique', port: 9109 },
            { name: 'heady-imagine', port: 9110 },
            { name: 'heady-stories', port: 9111 },
            { name: 'heady-sentinel', port: 9112 },
            { name: 'heady-vinci', port: 9113 },
            { name: 'heady-kinetics', port: 9114 },
            { name: 'heady-metrics', port: 9115 },
            { name: 'heady-logs', port: 9116 },
            { name: 'heady-traces', port: 9117 },
            { name: 'heady-desktop', port: 9118 },
            { name: 'heady-mobile', port: 9119 },
            { name: 'heady-chrome', port: 9120 },
            { name: 'heady-vscode', port: 9121 },
            { name: 'heady-jetbrains', port: 9122 },
            { name: 'heady-slack', port: 9123 },
            { name: 'heady-github-integration', port: 9124 },
        ].map(site => ({
            name: `site-${site.name}`,
            script: 'npx',
            args: `serve dist -l ${site.port} -s --no-clipboard`,
            cwd: `/home/headyme/sites/${site.name}`,
            instances: 1,
            exec_mode: 'fork',
            env: { NODE_ENV: 'production' },
            max_memory_restart: '128M',
            min_uptime: '5s',
            max_restarts: 3,
            restart_delay: 2000,
            watch: false,
            autorestart: true,
        })),
    ],
};
