name = "edge-auth-worker"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "$CLOUDFLARE_ACCOUNT_ID"

[env.production]
routes = [{ pattern = "auth.headysystems.com/*", zone_name = "headysystems.com" }]
[env.production.vars]
ENVIRONMENT = "production"
JWT_ISSUER = "headysystems.com"
AUTH_BACKEND = "https://manager.headysystems.com/api/auth"
