import principles = require("./lib/principles");
import spatial = require("./lib/spatial-embedder");
import octree = require("./lib/octree-manager");
import templates = require("./lib/template-engine");
import capacity = require("./lib/capacity-planner");
export declare let PHI: number;
export declare let PHI_INV: number;
export declare let PHI_SQ: number;
export declare let PHI_CUBE: number;
export declare let BASE: number;
export declare let LOG_BASE: number;
export declare let FIB: number[];
export declare let SpatialEmbedder: typeof import("./lib/spatial-embedder").SpatialEmbedder;
export declare let OctreeManager: typeof import("./lib/octree-manager").OctreeManager;
export declare let TemplateEngine: typeof import("./lib/template-engine").TemplateEngine;
export declare let CapacityPlanner: typeof import("./lib/capacity-planner").CapacityPlanner;
export declare let phiScale: typeof import("./lib/principles").phiScale;
export declare let goldenSplit: typeof import("./lib/principles").goldenSplit;
export declare let phiBackoff: typeof import("./lib/principles").phiBackoff;
export declare let phiThresholds: typeof import("./lib/principles").phiThresholds;
export declare let phiHarmonics: typeof import("./lib/principles").phiHarmonics;
export declare let toBase13: typeof import("./lib/principles").toBase13;
export declare let fromBase13: typeof import("./lib/principles").fromBase13;
export declare let log42: typeof import("./lib/principles").log42;
export declare let toTier: typeof import("./lib/principles").toTier;
export declare let capacityParams: typeof import("./lib/principles").capacityParams;
export declare let designTokens: typeof import("./lib/principles").designTokens;
export declare let goldenColor: typeof import("./lib/principles").goldenColor;
export declare let phiTiming: typeof import("./lib/principles").phiTiming;
export { principles, spatial, octree, templates, capacity };
//# sourceMappingURL=index.d.ts.map