import headyEnv = require("./heady-env");
import headyFetchModule = require("./heady-fetch");
import headyServerModule = require("./heady-server");
import headyJwt = require("./heady-jwt");
import headyCrypt = require("./heady-crypt");
import headySchedulerModule = require("./heady-scheduler");
import headyKvModule = require("./heady-kv");
import headyYaml = require("./heady-yaml");
export declare let parseEnv: typeof headyEnv.parse;
export declare let loadEnv: typeof headyEnv.loadEnv;
export declare let loadEnvFiles: typeof headyEnv.loadEnvFiles;
export declare let requireEnv: typeof headyEnv.requireEnv;
export declare let getEnv: typeof headyEnv.getEnv;
export declare let isProduction: typeof headyEnv.isProduction;
export declare let isTest: typeof headyEnv.isTest;
export declare let isDevelopment: typeof headyEnv.isDevelopment;
export declare let headyFetch: typeof headyFetchModule;
export declare let fetchGet: (url: string, options?: FetchOptions) => Promise<{
    status: number;
    headers: Object;
    body: string;
    json: Function;
    ok: boolean;
}>;
export declare let fetchPost: (url: string, body: any, options?: FetchOptions) => Promise<{
    status: number;
    headers: Object;
    body: string;
    json: Function;
    ok: boolean;
}>;
export declare let fetchPut: (url: any, body: any, options?: {}) => Promise<{
    status: number;
    headers: Object;
    body: string;
    json: Function;
    ok: boolean;
}>;
export declare let fetchPatch: (url: any, body: any, options?: {}) => Promise<{
    status: number;
    headers: Object;
    body: string;
    json: Function;
    ok: boolean;
}>;
export declare let fetchDelete: (url: any, options?: {}) => Promise<{
    status: number;
    headers: Object;
    body: string;
    json: Function;
    ok: boolean;
}>;
export declare let getCircuitStatus: typeof headyFetchModule.getCircuitStatus;
export declare let resetCircuit: typeof headyFetchModule.resetCircuit;
export declare let HeadyServer: typeof headyServerModule.HeadyServer;
export declare let HeadyRouter: typeof headyServerModule.HeadyRouter;
export declare let createServer: typeof headyServerModule.createServer;
export declare let MIME_TYPES: {
    '.html': string;
    '.htm': string;
    '.css': string;
    '.js': string;
    '.mjs': string;
    '.json': string;
    '.png': string;
    '.jpg': string;
    '.jpeg': string;
    '.gif': string;
    '.svg': string;
    '.ico': string;
    '.txt': string;
    '.md': string;
    '.pdf': string;
    '.woff': string;
    '.woff2': string;
    '.ttf': string;
    '.otf': string;
    '.webp': string;
    '.mp4': string;
    '.webm': string;
};
export declare let sign: typeof headyJwt.sign;
export declare let verify: typeof headyJwt.verify;
export declare let decode: typeof headyJwt.decode;
export declare let refreshToken: typeof headyJwt.refresh;
export declare let generateJwtId: typeof headyJwt.generateJwtId;
export declare let hash: typeof headyCrypt.hash;
export declare let hashSync: typeof headyCrypt.hashSync;
export declare let compare: typeof headycrypt.compare;
export declare let compareSync: typeof headycrypt.compareSync;
export declare let generateToken: typeof headyCrypt.generateToken;
export declare let generateApiKey: typeof headyCrypt.generateApiKey;
export declare let needsRehash: typeof headyCrypt.needsRehash;
export declare let timingSafeEqual: typeof headyCrypt.timingSafeEqual;
export declare let HeadyScheduler: typeof headySchedulerModule.HeadyScheduler;
export declare let defaultScheduler: headySchedulerModule.HeadyScheduler;
export declare let createScheduler: typeof headySchedulerModule.createScheduler;
export declare let parseCronExpression: typeof headySchedulerModule.parseCronExpression;
export declare let HeadyKV: typeof headyKvModule.HeadyKV;
export declare let createKV: typeof headyKvModule.createKV;
export declare let defaultStore: headyKvModule.HeadyKV;
export declare let parseYaml: (yamlStr: string) => any;
export declare let parseAllYaml: (yamlStr: string) => Array<any>;
export declare let stringifyYaml: (value: any, options?: {
    indent?: number | undefined;
    noRefs?: boolean | undefined;
}) => string;
export declare let yamlLoad: (yamlStr: string) => any;
export declare let yamlDump: (value: any, options?: {
    indent?: number | undefined;
    noRefs?: boolean | undefined;
}) => string;
export { headyEnv as env, headyJwt as jwt, headyCrypt as crypt, headyYaml as yaml };
//# sourceMappingURL=index.d.ts.map